version: '3.3'

services:
    
  next:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    tty: true
    volumes:
      - ./frontend:/app
    ports:
      - 3000:3000
    # command: sh -c "npm install && npm run dev"
    env_file:
      - frontend/.env.local
    networks:
      - supabase_network_next-type-app
    

  postgres:
    image: postgres:15.2
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_NAME: postgres 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_PORT: 5432
    networks:
      - supabase_network_next-type-app

volumes:
  postgres_data:

networks:
  supabase_network_next-type-app:
    external: true