FROM node:19-alpine3.15

WORKDIR /app

RUN apk update && apk add --no-cache python3 make g++

# COPY ./containers/react/entrypoint.sh /usr/local/bin/entrypoint.sh
# RUN chmod +x /usr/local/bin/entrypoint.sh

# ENTRYPOINT [ "/usr/local/bin/entrypoint.sh" ]